version: '3.8'
services:
  web:
    build: .
    command: gunicorn backend.goto_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.goto_backend.settings
      - DATABASE_URL=sqlite:///db.sqlite3
